language: rust
cache: cargo
matrix:
  include:
    - os: linux
      rust: 1.30.0
    - os: osx
      rust: 1.30.0
    - os: windows
      rust: 1.30.0
notifications:
  email:
    on_success: change
    on_failure: change
