[package]
name = "wasvm"
version = "0.2.1"
authors = ["Shinichi Kogai <kogai0121@gmail.com>"]

[dependencies]
hashbrown = "0.1"

[dev-dependencies]
wabt = "0.7.3"
flame = "0.2.2"

[[bin]]
name = "main"
path = "bin/main.rs"
