[package]
name = "wasvm"
version = "0.1.0"
authors = ["Shinichi Kogai <kogai0121@gmail.com>"]

[dependencies]

[dev-dependencies]
wabt = "0.7.1"
flame = "0.2.2"

[[bin]]
name = "main"
path = "bin/main.rs"
