[package]
name = "wasvm"
version = "0.1.0"
authors = ["Shinichi Kogai <kogai0121@gmail.com>"]

[dev-dependencies]
serde = "1.0.0"
serde_derive = "1.0.0"
serde_json = "1.0.0"

[[bin]]
name = "main"
path = "bin/main.rs"
