[package]
name = "wasvm"
version = "0.2.0"
authors = ["Shinichi Kogai <kogai0121@gmail.com>"]

[dependencies]
libm = "0.1.2"

[dependencies.hashbrown]
version = "0.1"
features = ["nightly"]

[dev-dependencies]
wabt = "0.7.3"
flame = "0.2.2"

[[bin]]
name = "main"
path = "bin/main.rs"
